[config]
mode = "dark"
scheme = "scheme-tonal-spot"

# [templates.waybar]
# input_path = "~/.config/matugen/templates/waybar.css"
# output_path = "~/.cache/matugen/waybar/colors.css"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland.lua"
output_path = "~/.cache/matugen/hyprland/colors.lua"

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell.qml"
output_path = "~/.cache/matugen/quickshell/Colors.qml"

[templates.wezterm]
input_path = "~/.config/matugen/templates/wezterm.lua"
output_path = "~/.cache/matugen/wezterm/colors.lua"

[templates.walker]
input_path = "~/.config/matugen/templates/walker.css"
output_path = "~/.cache/matugen/walker/colors.css"

