[config]
mode = "dark"
scheme = "scheme-tonal-spot"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.cache/matugen/waybar/colors.css"

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell.qml"
output_path = "~/.cache/matugen/quickshell/colors.qml"
