return {
    foreground = "{{colors.on_background.default.hex}}",
    background = "{{colors.background.default.hex}}",
    cursor_bg = "{{colors.primary.default.hex}}",
    cursor_border = "{{colors.primary.default.hex}}",
    cursor_fg = "{{colors.background.default.hex}}",
    selection_fg = "{{colors.on_secondary.default.hex}}",
    selection_bg = "{{colors.secondary.default.hex}}",
    ansi = {
        "{{colors.surface_variant.default.hex}}",
        "{{colors.primary.default.hex}}",
        "{{colors.tertiary.default.hex}}",
        "{{colors.secondary.default.hex}}",
        "{{colors.primary_container.default.hex}}",
        "{{colors.tertiary_container.default.hex}}",
        "{{colors.secondary_container.default.hex}}",
        "{{colors.outline.default.hex}}",
    },
    brights = {
        "{{colors.surface_variant.default.hex}}",
        "{{colors.primary.default.hex}}",
        "{{colors.tertiary.default.hex}}",
        "{{colors.secondary.default.hex}}",
        "{{colors.primary_container.default.hex}}",
        "{{colors.tertiary_container.default.hex}}",
        "{{colors.secondary_container.default.hex}}",
        "{{colors.foreground.default.hex}}",
    },
}
